name = "Daniel Jackson"
# avatar = "images/profile.png" # Avatar image. Default to "images/profile.webp".
bio = "Java, JavaScript, Full Stack Engineer, Economist"
company = "Company"
location = "NY"
# alternatives:
# location = "<a href='https://www.openstreetmap.org/search?query=Earth'>Earth</a>"
# location = "<a href='https://www.google.com/maps/search/Earth'>Earth</a>"
# about = "https://domain.tld" # The external about page. The internal about page will be used if not set.

[params]
  #layout = "compact"
